services:
  app:
    image: 'hvz-backend:latest'
    build:
      context: .
    container_name: hvz-backend
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
        - "8080:8080"

  db:
    image: 'postgres:15.2-alpine'
    container_name: hvz-db
    environment:
      - POSTGRES_USER=${PROD_DB_USERNAME}
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}